### ISSUE TITLE
Display and directory prefs errors

### ISSUE THREAD

**Issue by qg0** [rycus86/docker-pycharm#12]
The script from #4 with XSOCK and XAUTH, etc options:
```
docker run --rm
-v /tmp/.X11-unix:/tmp/.X11-unix
-v ~/.PyCharm:/root/.PyCharm
-v ~/.PyCharm.java:/root/.java
-v ~/.PyCharm.py3:/usr/local/lib/python3.6
-v ~/.PyCharm.share:/root/.local/share/JetBrains
-v ~/Project:/home/developer/Project
--name pycharm-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S')
-v /N:/N
-e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH *
rycus86/pycharm:latest
```

The result:
```
invalid reference format: repository name must be lowercase`
```

______________________________________________________________________

The original script with _DISPLAY=:0_.
Also I've tried to remove "-v" options for directories and change DISPLAY variable to ":1", ":0.1", etc. Anyway I know that it's definitely :0 because I am using this in the cron scripts.

```
docker run --rm \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.PyCharm:/home/developer/.PyCharm \
  -v ~/.PyCharm.java:/home/developer/.java \
  -v ~/.PyCharm.py2:/usr/local/lib/python2.7 \
  -v ~/.PyCharm.py3:/usr/local/lib/python3.7 \
  -v ~/.PyCharm.share:/home/developer/.local/share/JetBrains \
  -v ~/Project:/home/developer/Project \
  --name pycharm-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
rycus86/pycharm:latest
```

The result:

```
**OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.**

Invalid Config Directory: The IDE cannot create the directory.
Possible reason: parent directory is read-only or the user lacks necessary permissions.

If you have modified the 'idea.config.path' property, please make sure it is correct,
otherwise, please re-install the IDE.

-----
**Location: /home/developer/.PyCharmCE2019.3/config
java.nio.file.AccessDeniedException: /home/developer/.PyCharmCE2019.3/config
No protocol specified**

Also, a UI exception occurred on an attempt to show the above message:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/javax.swing.RepaintManager.<clinit>(RepaintManager.java:243)
        at java.desktop/javax.swing.JComponent.repaint(JComponent.java:4835)
        at java.desktop/java.awt.Component.repaint(Component.java:3412)
        at java.desktop/javax.swing.text.JTextComponent.setEditable(JTextComponent.java:1818)
        at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:323)
        at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:198)
        at java.desktop/javax.swing.JTextPane.<init>(JTextPane.java:87)
        at com.intellij.idea.Main.showMessage(Main.java:213)
        at com.intellij.idea.StartupUtil.checkDirectory(StartupUtil.java:449)
        at com.intellij.idea.StartupUtil.checkSystemDirs(StartupUtil.java:376)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:179)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

```
**OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.**
No protocol specified
2020-09-08 14:00:43,580 [    328]   WARN -        #com.intellij.idea.Main - java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable. 
java.util.concurrent.ExecutionException: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.intellij.idea.StartupUtil.runInEdtAndWait(StartupUtil.java:678)
        at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:227)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)
**Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.**
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1499)
        at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1318)
        at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$9(StartupUtil.java:265)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
Sep 08, 2020 2:00:44 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Sep 08, 2020 2:00:45 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/developer/.java/.userPrefs/prefs.xml
**2020-09-08 14:00:45,306 [   2054]   WARN -        #com.intellij.idea.Main - java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable. 
**java.util.concurrent.ExecutionException: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.****
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.intellij.idea.StartupUtil.runInEdtAndWait(StartupUtil.java:678)
        at com.intellij.idea.StartupUtil.showUserAgreementAndConsentsIfNeeded(StartupUtil.java:669)
        at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:231)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)
**Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.**
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1499)
        at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1318)
        at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$9(StartupUtil.java:265)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
**2020-09-08 14:00:45,647 [   2395]   WARN -        #com.intellij.idea.Main - java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable. 
java.util.concurrent.ExecutionException: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.**
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.intellij.idea.StartupUtil.runInEdtAndWait(StartupUtil.java:678)
        at com.intellij.idea.StartupUtil.lambda$showUserAgreementAndConsentsIfNeeded$15(StartupUtil.java:673)
        at com.intellij.ui.AppUIUtil.showConsentsAgreementIfNeeded(AppUIUtil.java:332)
        at com.intellij.idea.StartupUtil.showUserAgreementAndConsentsIfNeeded(StartupUtil.java:673)
        at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:231)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)
**Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.**
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1499)
        at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1318)
        at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$9(StartupUtil.java:265)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
**2020-09-08 14:00:45,714 [   2462]  ERROR - llij.ide.plugins.PluginManager - Could not initialize class sun.awt.X11.XToolkit 
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit**
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1348)
        at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:235)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-08 14:00:45,716 [   2464]  ERROR - llij.ide.plugins.PluginManager - PyCharm 2019.3.2  Build #PC-193.6015.41 
2020-09-08 14:00:45,717 [   2465]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-09-08 14:00:45,718 [   2466]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 

Start Failed: Internal error. Please refer to http://jb.gg/ide/critical-startup-errors

**java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit**
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1348)
        at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:235)
        at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:213)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
        at java.base/java.lang.Thread.run(Thread.java:834)

-----
JRE 11.0.5+10-b520.30 amd64 by JetBrains s.r.o
/opt/pycharm/jbr

**Also, a UI exception occurred on an attempt to show the above message:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE**
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/javax.swing.RepaintManager.<clinit>(RepaintManager.java:243)
        at java.desktop/javax.swing.JComponent.repaint(JComponent.java:4835)
        at java.desktop/java.awt.Component.repaint(Component.java:3412)
        at java.desktop/javax.swing.text.JTextComponent.setEditable(JTextComponent.java:1818)
        at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:323)
        at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:198)
        at java.desktop/javax.swing.JTextPane.<init>(JTextPane.java:87)
        at com.intellij.idea.Main.showMessage(Main.java:213)
        at com.intellij.idea.Main.showMessage(Main.java:189)
        at com.intellij.ide.plugins.StartupAbortedException.processException(StartupAbortedException.java:78)
        at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:48)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rycus86** [comment]
The error here is a bit misleading, it's not a problem with DISPLAY I think, but with the mounted folders being owned by root instead of your user. Can you chown them and try again?

**Comment by qg0** [comment]
I've added the new system user - "user" and got this:

```
user@acer:~/Desktop> sudo sh pych.sh 
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

Invalid Config Directory: The IDE cannot create the directory.
Possible reason: parent directory is read-only or the user lacks necessary permissions.

If you have modified the 'idea.config.path' property, please make sure it is correct,
otherwise, please re-install the IDE.

-----
Location: /home/developer/.PyCharmCE2019.3/config
java.nio.file.AccessDeniedException: /home/developer/.PyCharmCE2019.3/config
```

![image](https://user-images.githubusercontent.com/919099/92528255-a8b69700-f252-11ea-971c-5f9c48cd0818.png)

Without "sudo" it doesn't work:
```
user@acer:~/Desktop> sh pych.sh 
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=pycharm-3512934d-20200909-041311: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.


```

**Comment by rycus86** [comment]
You don't need a new user on the host system, just to have the folders attached to the container owned by __your__ user on the host.

```
sudo chown -R $(uid -u):$(uid -g) ~/.PyCharm
sudo chown -R $(uid -u):$(uid -g) ~/.PyCharm.java
sudo chown -R $(uid -u):$(uid -g) ~/.PyCharm.py3
sudo chown -R $(uid -u):$(uid -g) ~/.PyCharm.share
sudo chown -R $(uid -u):$(uid -g)  ~/Project
```

(just double-check the `uid` from above, not 100% sure on its usage)

**Comment by qg0** [comment]
It's not working. I have the same problem. And it's just $(id -u) on my system.
Anyway it's a good idea to add this info to the Readme file?

**Comment by rycus86** [comment]
Ah yes, `id` is what I was thinking of.
Is it still giving the same problem?
I wonder if PyCharm started using a new config directory I'm not aware of and that's failing here. 🤔

**Comment by rycus86** [comment]
Oh, I just saw that you're mapping directories in the container under `/root`, why is that?

**Comment by qg0** [comment]
It's a copy-paste from the #4 issue by @VincentChong123
